# Generated by Django 5.0.3 on 2024-03-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_livre_date_sortie_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='livres',
            field=models.ManyToManyField(related_name='paniers', to='api.livre'),
        ),
    ]
