# Generated by Django 5.0.3 on 2024-03-15 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_panier_livres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='livres',
        ),
        migrations.CreateModel(
            name='LignePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.livre')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligne_paniers', to='api.panier')),
            ],
        ),
    ]
